### ISSUE TITLE
v3.6.0 didn't contain the router ID hash feature

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/node#194]
## Possible Solution

Looks like a missing confd pin update.  confd is pinned to 26b10ae37d6e3209cd8b6a5804a6562a46138183 but should be b0bf8c8109348dde63db22e2f074a392a653c10c

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* calico/node version: v3.6.0
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
This will be in v3.6.1 - here's the PR: https://github.com/projectcalico/node/pull/198

**Comment by mpfisterUniBE** [comment]
> This will be in v3.6.1 - here's the PR: #198

Still seems to be missing in v3.6.1 as the string "hash" in CALICO_ROUTER_ID still adds "hash" instead of an IP into the bird.cfg

```[root@k8s-sidl5-m1 ~]# kubectl get pods -n kube-system -o=custom-columns=NAME:.metadata.name,IMAGE:.spec.containers[*].image | egrep 'NAME|calico'
NAME                                                   IMAGE
calico-kube-controllers-55df754b5d-b92lp               calico/kube-controllers:v3.6.1
calico-node-82q8t                                      calico/node:v3.6.1
calico-node-f74x9                                      calico/node:v3.6.1
calico-node-hnz4h                                      calico/node:v3.6.1
calico-node-xr89q                                      calico/node:v3.6.1
```

```
[root@k8s-sidl5-m1 ~]# kubectl exec -n kube-system calico-node-82q8t -- cat /etc/calico/confd/config/bird.cfg
# Generated by confd
include "bird_aggr.cfg";
include "bird_ipam.cfg";

router id hash;
[SNIP]
```

=> bird: /etc/calico/confd/config/bird.cfg, line 5: Number or IPv4 address constant expected.

**Comment by fasaxc** [comment]
@mpfisterUniBE Hmm, that's the IPv4 config file, which we didn't update.  Can you confirm if this is working in the bird6.cfg?  I was expecting BIRDv4 not to run in an IPv6-only set-up; @caseydavenport is that what you'd expect?

**Comment by mpfisterUniBE** [comment]
@fasaxc Birdv4 does indeed run in a IPv6-only deployment and as the configcheck fails the healthcheck does as well what causes the calico-kube-controller to never actually start up.

This is why some of us came up with a solution of deploying a DeamonSet init container for calico to set an IPv4 routerid on each node within the bird(v4).cfg.
=> https://github.com/projectcalico/calico/issues/2229#issuecomment-435430481

The Birdv6 config is completely fine (oh and as I just realize the hash feature works perfectly fine there as well):
```[root@k8s-sidl5-m1 ~]# kubectl exec -n kube-system calico-node-xt248 -- cat /etc/calico/confd/config/bird6.cfg
# Generated by confd
include "bird6_aggr.cfg";
include "bird6_ipam.cfg";
router id 104.67.18.5;  # Use IP address generated by nodename's hash
```

So yes, the question is, why is Birdv4 even running. Or did I miss something in my config?

```
         env:
            # Use Kubernetes API as the backing datastore.
            - name: DATASTORE_TYPE
              value: "kubernetes"
            # Wait for the datastore.
            - name: WAIT_FOR_DATASTORE
              value: "true"
            # Set based on the k8s node name.
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # Choose the backend to use.
            - name: CALICO_NETWORKING_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: calico_backend
            # Cluster type to identify the deployment type
            - name: CLUSTER_TYPE
              value: "k8s,bgp"
            # Auto-detect the BGP IP address.
            - name: IP
              value: "none"
            # Enable IPIP
            - name: CALICO_IPV4POOL_IPIP
              value: "Always"
            # Set MTU for tunnel device used if ipip is enabled
            - name: FELIX_IPINIPMTU
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: veth_mtu
            # The default IPv4 pool to create on startup if none exists. Pod IPs will be
            # chosen from this range. Changing this value after installation will have
            # no effect. This should fall within `--cluster-cidr`.
            - name: CALICO_IPV4POOL_CIDR
              value: "192.168.0.0/16"
            - name: CALICO_IPV6POOL_CIDR
              value: "2001:620:400:282::/112"
            - name: IP6
              value: "autodetect"
            - name: CALICO_ROUTER_ID
              value: "hash"
            # Disable file logging so `kubectl logs` works.
            - name: CALICO_DISABLE_FILE_LOGGING
              value: "true"
            # Set Felix endpoint to host default action to ACCEPT.
            - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
              value: "ACCEPT"
            # Disable IPv6 on Kubernetes.
            - name: FELIX_IPV6SUPPORT
              value: "true"
            # Set Felix logging to "info"
            - name: FELIX_LOGSEVERITYSCREEN
              value: "info"
            - name: FELIX_HEALTHENABLED
              value: "true"
```
