### ISSUE TITLE
[RHEL 8.0]Readiness probe failed: HTTP probe failed with statuscode: 503(kernelversion:4.18.0-80.11.2.el8_0.x86_64)

### ISSUE THREAD

**Issue by Aisuko** [projectcalico/node#383]
## Expected Behavior

All containers were included in the canal pod would ready,

```
NAME                                      READY   STATUS             RESTARTS   AGE
canal-7cmkv                               2/2     Running            0          32m
canal-k8h64                               1/2     Running            0          32m
canal-sb7n9                               1/2     Running            0          32m
canal-xhkhg                               1/2     Running            0          32m
coredns-8b4654764-6bvwm                   1/1     Running            0          32m
coredns-autoscaler-84766fbb4-vcxlb        1/1     Running            0          32m
metrics-server-59c6fd6767-dgq6j           0/1     CrashLoopBackOff   9          32m
rke-coredns-addon-deploy-job-hrnp7        0/1     Completed          0          32m
rke-ingress-controller-deploy-job-knw2x   0/1     Completed          0          3d23h
rke-metrics-addon-deploy-job-qq8d7        0/1     Completed          0          3d23h
rke-network-plugin-deploy-job-8cxtn       0/1     Completed          0          3d23h
```

## Current Behavior

I always get the error from the container `calico-node:v3.7.4` like below

```
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  55m                 default-scheduler  Successfully assigned kube-system/canal-k8h64 to worker2
  Normal   Pulled     55m                 kubelet, worker2   Container image "rancher/calico-cni:v3.7.4" already present on machine
  Normal   Created    55m                 kubelet, worker2   Created container install-cni
  Normal   Started    55m                 kubelet, worker2   Started container install-cni
  Normal   Pulled     55m                 kubelet, worker2   Container image "rancher/calico-node:v3.7.4" already present on machine
  Normal   Created    55m                 kubelet, worker2   Created container calico-node
  Normal   Started    55m                 kubelet, worker2   Started container calico-node
  Normal   Pulled     55m                 kubelet, worker2   Container image "rancher/coreos-flannel:v0.11.0" already present on machine
  Normal   Created    55m                 kubelet, worker2   Created container kube-flannel
  Normal   Started    55m                 kubelet, worker2   Started container kube-flannel
  Warning  Unhealthy  45m (x5 over 50m)   kubelet, worker2   Readiness probe failed: Get http://localhost:9099/readiness: dial tcp [::1]:9099: connect: connection refused
  Warning  Unhealthy  5s (x320 over 55m)  kubelet, worker2   Readiness probe failed: HTTP probe failed with statuscode: 503
```

## Possible Solution

In fact, I do not have any idea about this.

## Steps to Reproduce (for bugs)

Use rancher rke version=0.3.2 deploy Kubernetes=1.15.5, I will upload the config file of rke and the log message file.

## Context

I believe that can make the nodes communication get the error.

## Your Environment

* calico/node version:

  `rancher/calico-node:v3.7.4` The image same as the calico-node:v3.7.4, but I'm not actually sure about this.

* Operating System and version:

```
NAME      STATUS   ROLES               AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                               KERNEL-VERSION                CONTAINER-RUNTIME
master    Ready    controlplane,etcd   4d    v1.15.5   10.16.18.171   <none>        Red Hat Enterprise Linux 8.0 (Ootpa)   4.18.0-80.11.2.el8_0.x86_64   docker://19.3.5
worker1   Ready    worker              4d    v1.15.5   10.16.18.172   <none>        Red Hat Enterprise Linux 8.0 (Ootpa)   4.18.0-80.11.2.el8_0.x86_64   docker://19.3.5
worker2   Ready    worker              4d    v1.15.5   10.16.18.173   <none>        Red Hat Enterprise Linux 8.0 (Ootpa)   4.18.0-80.11.2.el8_0.x86_64   docker://19.3.5
worker3   Ready    worker              4d    v1.15.5   10.16.18.174   <none>        Red Hat Enterprise Linux 8.0 (Ootpa)   4.18.0-80.11.2.el8_0.x86_64   docker://19.3.5
```
* Link to your project (optional):

```
nodes:
- address: 10.16.18.171
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - etcd
  hostname_override: master
  user: rancher
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: 10.16.18.172
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: worker1
  user: rancher
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: 10.16.18.173
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: worker2
  user: rancher
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: 10.16.18.174
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: worker3
  user: rancher
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    snapshot: true
    retention: "12h"
    creation: "120m0s"
    backup_config: null
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
  kubelet:
    image: ""
    extra_args:
      network-plugin: "cni"
    extra_binds: []
    extra_env: []
    cluster_domain: cluster.huggle
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
  kubeproxy:
    image: ""
    extra_args:
      proxy-mode: ipvs
    extra_binds:
      - "/lib/modules:/lib/modules:ro"
    extra_env: []
network:
  plugin: canal
  options:
    canal_flannel_backend_type: host-gw
  node_selector: {}
authentication:
  strategy: x509
  sans: []
  webhook: null
addons: ""
addons_include: []
system_images:
  etcd: rancher/coreos-etcd:v3.3.10-rancher1
  alpine: rancher/rke-tools:v0.1.50
  nginx_proxy: rancher/rke-tools:v0.1.50
  cert_downloader: rancher/rke-tools:v0.1.50
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.50
  kubedns: rancher/k8s-dns-kube-dns:1.15.0
  dnsmasq: rancher/k8s-dns-dnsmasq-nanny:1.15.0
  kubedns_sidecar: rancher/k8s-dns-sidecar:1.15.0
  kubedns_autoscaler: rancher/cluster-proportional-autoscaler:1.3.0
  coredns: rancher/coredns-coredns:1.6.2
  coredns_autoscaler: rancher/cluster-proportional-autoscaler:1.3.0
  kubernetes: rancher/hyperkube:v1.15.5-rancher1
  flannel: rancher/coreos-flannel:v0.11.0-rancher1
  flannel_cni: rancher/flannel-cni:v0.3.0-rancher5
  calico_node: rancher/calico-node:v3.7.4
  calico_cni: rancher/calico-cni:v3.7.4
  calico_controllers: rancher/calico-kube-controllers:v3.7.4
  calico_ctl: rancher/calico-ctl:v2.0.0
  calico_flexvol: ""
  canal_node: rancher/calico-node:v3.7.4
  canal_cni: rancher/calico-cni:v3.7.4
  canal_flannel: rancher/coreos-flannel:v0.11.0
  canal_flexvol: ""
  weave_node: weaveworks/weave-kube:2.5.2
  weave_cni: weaveworks/weave-npc:2.5.2
  pod_infra_container: rancher/pause:3.1
  ingress: rancher/nginx-ingress-controller:nginx-0.25.1-rancher1
  ingress_backend: rancher/nginx-ingress-controller-defaultbackend:1.5-rancher1
  metrics_server: rancher/metrics-server:v0.3.3
  windows_pod_infra_container: rancher/kubelet-pause:v0.1.3
ssh_key_path: ~/.ssh/id_rsa
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: false
kubernetes_version: ""
private_registries: []
ingress:
  provider: "nginx"
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
cluster_name: ""
cloud_provider:
  name: ""
prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
monitoring:
  provider: ""
  options: {}
  node_selector: {}
restore:
  restore: false
  snapshot_name: ""
dns:
  provider: coredns
```

[logs.log](https://github.com/projectcalico/node/files/3931689/logs.log)

**Comment by tmjd** [comment]
From the logs it is showing that the iptables-restore command is failing, and I'm not sure what would cause that. @fasaxc any thoughts why that might be? I took one of the failed inputs and got it formatted nicely and the line that is failing on is 41 which seems to be the COMMIT at the end.

Also I see that there are Cilium chains in the "Current state of iptables" that felix prints before panicing, could the two plugins be interfering with each other?

**Comment by fasaxc** [comment]
COMMIT failure usually means that another application has changed iptables in parallel with calico and the kernel rejects that.  We retry a few times though so it's very unusual, especially at such small scale.  Maybe rancher has some super-aggressive iptables updates going on?

**Comment by fasaxc** [comment]
I tried executing the iptables commands manually here by loading up the `Current state of iptables` in a container and then applying the delta iptables commands.  They applied cleanly so it looks like a concurrent modification issue or some other kernel issue.

**Comment by Aisuko** [comment]
In the cluster, I used `canal_flannel_backend_type: host-gw` as `canal`'s `options`, the  `proxy-mode: ipvs` and `"/lib/modules:/lib/modules:ro"` as `kubeproxy`'s `extra_binds`.

* I tried to deploy `cilium` and `Hubble` and hit some issue. So, these application has had been removed.

```
[root@cont-29-rdc ~]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:9e:0f:ff brd ff:ff:ff:ff:ff:ff
    inet 10.16.18.171/24 brd 10.16.18.255 scope global noprefixroute ens192
       valid_lft forever preferred_lft forever
    inet6 fe80::7530:1797:8588:310a/64 scope link dadfailed tentative noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fe80::67ea:eb6f:5610:e146/64 scope link dadfailed tentative noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fe80::3949:b6f9:885a:8ff0/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:de:fc:73:a2 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:deff:fefc:73a2/64 scope link
       valid_lft forever preferred_lft forever
26: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default
    link/ether 9a:5c:e6:cc:78:50 brd ff:ff:ff:ff:ff:ff
    inet 10.43.0.1/32 brd 10.43.0.1 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.43.0.10/32 brd 10.43.0.10 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.43.84.45/32 brd 10.43.84.45 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.43.99.40/32 brd 10.43.99.40 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
71: cilium_net@cilium_host: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether aa:e4:8e:32:3a:1c brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a8e4:8eff:fe32:3a1c/64 scope link
       valid_lft forever preferred_lft forever
72: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 4e:22:3b:f8:c7:06 brd ff:ff:ff:ff:ff:ff
    inet 10.42.0.242/32 scope link cilium_host
       valid_lft forever preferred_lft forever
    inet6 fe80::4c22:3bff:fef8:c706/64 scope link
       valid_lft forever preferred_lft forever
73: cilium_vxlan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 7e:dd:e3:94:dc:1b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::7cdd:e3ff:fe94:dc1b/64 scope link
       valid_lft forever preferred_lft forever
[root@cont-29-rdc ~]# ipvsadm -ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.43.0.1:443 rr
  -> 10.16.18.171:6443            Masq    1      2          0
TCP  10.43.0.10:53 rr
  -> 10.42.3.7:53                 Masq    1      0          0
TCP  10.43.0.10:9153 rr
  -> 10.42.3.7:9153               Masq    1      0          0
TCP  10.43.84.45:443 rr
TCP  10.43.99.40:80 rr
  -> 10.42.3.3:8080               Masq    1      0          0
UDP  10.43.0.10:53 rr
  -> 10.42.3.7:53                 Masq    1      0          0
[root@cont-29-rdc ~]# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (1 references)
target     prot opt source               destination

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere
# Warning: iptables-legacy tables present, use iptables-legacy to see them
```

**Comment by fasaxc** [comment]
Might be worth a reboot after removing the other CNI plugins.  Also worth checking none of the itpables or interface config got persisted to `/etc/`.

**Comment by Aisuko** [comment]
I have made a choice from rehl8 to rehl7 with kernel version `3.10.0-1062.el7.x86_64`and it works well. So, I changed the issue title in order to show the issue related to rehl 8.

```
 ~/Documents/cluster-config/hubble7   dev ● ?  kubectl get nodes -owide
NAME      STATUS   ROLES               AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                                      KERNEL-VERSION           CONTAINER-RUNTIME
master    Ready    controlplane,etcd   52m   v1.15.5   10.16.18.173   <none>        Red Hat Enterprise Linux Server 7.5 (Maipo)   3.10.0-1062.el7.x86_64   docker://19.3.2
worker1   Ready    worker              52m   v1.15.5   10.16.18.174   <none>        Red Hat Enterprise Linux Server 7.5 (Maipo)   3.10.0-1062.el7.x86_64   docker://19.3.2
```


```
 ~/Documents/cluster-config/hubble7   dev ● ?  kubectl get pods --all-namespaces
NAMESPACE       NAME                                      READY   STATUS      RESTARTS   AGE
ingress-nginx   default-http-backend-5bcc9fd598-kj9fm     1/1     Running     0          6m8s
ingress-nginx   nginx-ingress-controller-2jr68            1/1     Running     0          6m8s
kube-system     canal-2m2s2                               2/2     Running     0          6m22s
kube-system     canal-z2r6z                               2/2     Running     0          6m22s
kube-system     coredns-8b4654764-vc7vz                   1/1     Running     0          6m18s
kube-system     coredns-autoscaler-84766fbb4-lf8cx        1/1     Running     0          6m17s
kube-system     metrics-server-59c6fd6767-d8tkh           1/1     Running     0          6m13s
kube-system     rke-coredns-addon-deploy-job-sdwj5        0/1     Completed   0          6m19s
kube-system     rke-ingress-controller-deploy-job-nk65q   0/1     Completed   0          6m9s
kube-system     rke-metrics-addon-deploy-job-x762l        0/1     Completed   0          6m14s
kube-system     rke-network-plugin-deploy-job-k6btr       0/1     Completed   0          6m24s
```

**Comment by Aisuko** [comment]
> Might be worth a reboot after removing the other CNI plugins. Also worth checking none of the iptables or interface config got persisted to `/etc/`.

I followed your advice to remove CNI plugins and Kubernetes components container before reboot. And redeploy the Kubernetes cluster,  but there always has the same issue.

**Comment by tmjd** [comment]
For RHEL 8 I believe the iptables backend switched to the nft backend (from legacy). That means that calico v3.7 will not work with it. With calico v3.9 the backend is configurable through an environment variable (which is problematic for a mixed deployment) and the next Calico release (v3.12) will have an auto detected backend.

**Comment by immanuelfodor** [comment]
I ran into the same issue with an RKE deployed k8s cluster on CentOS 8, calico pods were unhealthy but still running. 

If anyone is getting the latest RKE version programatically, please pay attention that the latest handle of Github doesn't always return the actual latest RKE version as they regularly push updates to previous versions, too. Right now the latest stable RKE version is v1.1.0 while https://github.com/rancher/rke/releases/latest returns v0.2.0. In this case, v0.2.0 deploys calico-node v3.7, and v1.1.0 deploys v3.13.0. 

Upgrading the RKE binary generated a new cluster.yml with the current calico-node version that fixes the unhealthy state according to @tmjd 's previous comment. Thank you so much for the guidance!

For reference, Ansible tasks to get the "true" latest RKE version, adjust to your platform or preference if needed:

```yaml
- name: Get latest stable RKE version
  shell:
    cmd: |
      curl -s https://api.github.com/repos/rancher/rke/releases | grep download_url | grep linux-amd64 | grep -v '\-rc' | grep -oE 'v[0-9]+(\.[0-9]+){2}' | uniq | sort -r | head -n 1
    warn: false
  register: rke_latest

- name: Get latest stable Linux RKE binary
  get_url:
    url: 'https://github.com/rancher/rke/releases/download/{{ rke_latest.stdout }}/rke_linux-amd64'
    dest: /usr/local/bin/rke
    mode: '0755'
```
