### ISSUE TITLE
(v3.13.4)IPIP set cross-subnet, nodes in the same cidr still uses tunl0 iface to communicate

### ISSUE THREAD

**Issue by njuptlzf** [projectcalico/node#563]
IPIP set cross-subnet, nodes in the same cidr still uses tunl0 iface to communicate

## Expected Behavior

node in the same cdir communicates through the env IP interface(ens8)
node in the different cdir communicates through the tunl0 interface

## Current Behavior

$ route -n
Kernel IP routing table
```
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.122.1   0.0.0.0         UG    0      0        0 ens8
169.254.0.0     0.0.0.0         255.255.0.0     U     1003   0        0 ens8
169.254.0.0     0.0.0.0         255.255.0.0     U     1004   0        0 ens9
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.22.73.0     192.168.122.70  255.255.255.192 UG    0      0        0 tunl0    <------------
172.22.132.192  0.0.0.0         255.255.255.192 U     0      0        0 *
172.22.132.196  0.0.0.0         255.255.255.255 UH    0      0        0 calibdf597a306f
172.22.155.0    192.168.122.71  255.255.255.192 UG    0      0        0 tunl0    <-----------
192.168.122.0   0.0.0.0         255.255.255.0   U     0      0        0 ens8

```
env:
```
cat /etc/kubernetes/calico_env/env

IP=192.168.122.69
IP6=none
```

calico-node config:
```
containers:
  - args:
    - cat /etc/calico/env/env && export $(cat /etc/calico/env/env) && start_runit
    command:
    - /bin/sh
    - -c
    env:
    - name: CALICO_IPV4POOL_CIDR
      value: 172.22.0.0/16
    - name: CALICO_IPV6POOL_CIDR
      value: fd03::0/112
    - name: CALICO_IPV4POOL_IPIP
      value: cross-subnet            <------------
    - name: FELIX_IPV6SUPPORT
      value: "true"
    - name: CALICO_IPV6POOL_NAT_OUTGOING
      value: "true"
    - name: DATASTORE_TYPE
      value: kubernetes
    - name: WAIT_FOR_DATASTORE
      value: "true"
    - name: NODENAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: CALICO_NETWORKING_BACKEND
      valueFrom:
        configMapKeyRef:
          key: calico_backend
          name: calico-config
    - name: CLUSTER_TYPE
      value: k8s,bgp
    - name: CALICO_DISABLE_FILE_LOGGING
      value: "true"
    - name: CALICO_K8S_NODE_REF
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: CALICO_MANAGE_CNI
      value: "true"
    - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
      value: ACCEPT
    - name: FELIX_HEALTHENABLED
      value: "true"
    - name: FELIX_LOGSEVERITYSCREEN
      value: info
    - name: FELIX_IPINIPMTU
      value: "1440"
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* calico/node version:
* Operating System and version:
* Link to your project (optional):
