### ISSUE TITLE
CALICO_ADVERTISE_CLUSTER_IPS is depracted replace it with bgpconfiguration

### ISSUE THREAD

**Issue by misi** [projectcalico/node#600]
CALICO_ADVERTISE_CLUSTER_IPS is deprecated use instead of it BGPConfiguration option.
It conflicts and prevented calico advertise BGPConfiguration work properly.

See: https://docs.projectcalico.org/networking/advertise-service-ips
`
Note: In earlier versions of Calico, and for IPv4 only, service cluster IP advertisement was configured via the environment variable CALICO_ADVERTISE_CLUSTER_IPS. That environment variable takes precedence over any serviceClusterIPs configured in the default BGPConfiguration. We recommend replacing the deprecated CALICO_ADVERTISE_CLUSTER_IPS with BGPConfiguration.
`
## Expected Behavior
Create bgpcofinguration like below, instead of using the deprecated environment variable, and so please remove CALICO_ADVERTISE_CLUSTER_IPS deprecated environment variable.
```
calicoctl create -f - <<EOF
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  serviceClusterIPs:
  - cidr: 10.96.0.0/16
  - cidr: fd00:1234::/112
```
## Current Behavior
Does not advertise BGP service ip properly because conflicts with bgpconfiguration.

## Possible Solution
Remove deprecated env var 
Add bgpconfiguration with advertised serviceClusterIP cidrs

## Steps to Reproduce (for bugs)
Setup calico where service ip addresses are advertised to external peers

## Context
Try to setup calico to advertise service ip and external ip

## Your Environment
vagrant + ubuntu 18.04
