### ISSUE TITLE
Request to set NetworkUnavailable condition on calico-node shutdown

### ISSUE THREAD

**Issue by bradbehle** [projectcalico/node#823]
We are hitting a scenario where on a Calico update (rolling update of calico-node on a 150 node cluster), new pods are being scheduled and started on Nodes where calico-node is slow to restart (due to an overloaded scheduler we think), and these new pods do not have networking when they start up.

If calico-node set the NetworkUnavailable node condition to true when calico-node was ended, then this problem would be avoided because (non-host-netwowrk) pods would not be scheduled to a node without a calico-node pod that was running (or at least in the process of starting up).  We see that NetworkUnavailable is set to false when calico-node starts up, but we don't see anywhere it is set to true when calico-node is ended (or when it is in a non-working state such as when it can't make BGP connections to any other nodes).

This seems like a safe thing to do at least on calico-node shut down, because:
1. It will get set back to NetworkUnavailable=false whwen calico-node starts back up
2. Just setting this condition should taint the node so new pods won't be scheduled, but I don't believe will do anything to evict existing pods (although I haven't tested that out yet since I can't find a manual way to set this condition)

In a normal cluster this won't have a big impact since calico-node seems to start/restart quickly, but during an update or other cases where the cluster is under resource pressure, it could make a big difference in the stability of applications running in the cluster

## Expected Behavior
Set NetworkUnavailable=True when calico-node is shut down

## Current Behavior
NetworkUnavailable remains False when calico-node is shut down

## Steps to Reproduce (for bugs)
To recreate or test this scenario, you can do the following (thanks to @rtheis for these steps):

Apply this daemonset that just verifies that pods that are running when a calico-node rolling update occurs continue to have network connectivity:

```
kubectl apply -f - << EOF
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    name: pod-network-test-old
  name: pod-network-test-old
spec:
  selector:
    matchLabels:
      name: pod-network-test-old
  template:
    metadata:
      labels:
        name: pod-network-test-old
    spec:
      containers:
      - name: pod-network-test-old
        image: k8s.gcr.io/echoserver:1.10
        command: ["sh", "-c", "while true ; do date -u ; curl --silent --output /dev/null --show-error -k --max-time 10 --connect-timeout 7 https://kubernetes.default/version || echo 'ERROR: Master verfication failed.'; sleep 1 ; done"]
EOF
```

Then to get recent logs from each of these pods to verify network connectivity:

```
kubectl logs -l name=pod-network-test-old --tail=20
```

Then edit the calico-node daemonset, and make the following two changes:

`kubectl edit ds -n kube-system calico-node`

1. Set a rolling update strategy with maxUnavailable=1 so calico-node pods restart one at a time:

```
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
```

2. Add an init container in front of the install-cni init container that just sleeps for a few minutes, to simulate a delay in calico-node starting up:

```
      - command: ["sh", "-c", "sleep 300"]
        name: sleep
        image: k8s.gcr.io/echoserver:1.10
```

Once you save the changes, the calico-node pods should be restarted one by one, and they should delay for 300 seconds before starting up.  During this time, you can test to see that new pods are scheduled to this node, but do not have networking.  To do this, get the node name that calico-node is starting on, and run a pod like this (assuming the node name is 10.189.61.55):

```
export WORKERNODE=10.189.61.55

kubectl apply -f - << EOF
apiVersion: v1
kind: Pod
metadata:
  name: pod-network-test-${WORKERNODE}
spec:
  containers:
  - name: pod-network-test
    image: k8s.gcr.io/echoserver:1.10
    command: ["sh", "-c", "while true ; do date -u ; curl --silent --output /dev/null --show-error -k --max-time 10 --connect-timeout 7 https://kubernetes.default/version || echo 'ERROR: Master verfication failed.'; sleep 1 ; done"]
  nodeSelector:
    kubernetes.io/hostname: ${WORKERNODE}
EOF
```

Then to follow the logs to see the connection failures until calico-node starts up, you can use this:

`kubectl logs pod-network-test-${WORKERNODE} --tail=10 -f`

## Your Environment
* calico/node version: Seen this from Calico 3.12 - 3.17
* Operating System and version: Ubuntu
* Link to your project (optional):
